from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['empresa', 'tipo_alta', 'proveedor', 'contribuyente', 'razon_social', 'rfc', 'curp', 'regimen_capital', 'nombre_comercial', 'regimen_fiscal', 'uso_cdfi', 'representante_legal', 'correo_contacto', 'celular', 'correo_pagos', 'sitio_web', 'rubro', 'tipo_operacion', 'dias_credito', 'monto_credito', 'retencion_iva', 'retencion_isr', 'iva_frontera', 'calle', 'numero_exterior', 'numero_interior', 'codigo_postal', 'colonia', 'municipio', 'ciudad', 'estado', 'pais', 'banco', 'cuenta', 'moneda', 'clabe', 'banco2', 'cuenta2', 'moneda2', 'clabe2', 'constancia_situacion_fiscal', 'estado_cuenta_bancario']
        widgets = {
            'empresa': forms.TextInput(attrs={'class':'form-control'}),
            'tipo_alta': forms.TextInput(attrs={'class':'form-control'}),
            'proveedor': forms.TextInput(attrs={'class':'form-control'}),
            'contribuyente': forms.TextInput(attrs={'class':'form-control'}),
            'razon_social': forms.TextInput(attrs={'class':'form-control'}),
            'rfc': forms.TextInput(attrs={'class':'form-control'}),
            'curp': forms.TextInput(attrs={'class':'form-control'}),
            'regimen_capital': forms.TextInput(attrs={'class':'form-control'}),
            'nombre_comercial': forms.TextInput(attrs={'class':'form-control'}),
            'regimen_fiscal': forms.TextInput(attrs={'class':'form-control'}),
            'uso_cdfi': forms.TextInput(attrs={'class':'form-control'}),
            'representante_legal': forms.TextInput(attrs={'class':'form-control'}),
            'correo_contacto': forms.TextInput(attrs={'class':'form-control'}),
            'celular': forms.TextInput(attrs={'class':'form-control'}),
            'correo_pagos': forms.TextInput(attrs={'class':'form-control'}),
            'sitio_web': forms.TextInput(attrs={'class':'form-control'}),
            'rubro': forms.TextInput(attrs={'class':'form-control'}),
            'tipo_operacion': forms.TextInput(attrs={'class':'form-control'}),
            'dias_credito': forms.TextInput(attrs={'class':'form-control'}),
            'monto_credito': forms.TextInput(attrs={'class':'form-control'}),
            'retencion_iva': forms.TextInput(attrs={'class':'form-control'}),
            'retencion_isr': forms.TextInput(attrs={'class':'form-control'}),
            'iva_frontera': forms.TextInput(attrs={'class':'form-control'}),
            'calle': forms.TextInput(attrs={'class':'form-control'}),
            'numero_exterior': forms.TextInput(attrs={'class':'form-control'}),
            'numero_interior': forms.TextInput(attrs={'class':'form-control'}),
            'codigo_postal': forms.TextInput(attrs={'class':'form-control'}),
            'colonia': forms.TextInput(attrs={'class':'form-control'}),
            'municipio': forms.TextInput(attrs={'class':'form-control'}),
            'ciudad': forms.TextInput(attrs={'class':'form-control'}),
            'estado': forms.TextInput(attrs={'class':'form-control'}),
            'pais': forms.TextInput(attrs={'class':'form-control'}),
            'banco': forms.TextInput(attrs={'class':'form-control'}),
            'cuenta': forms.TextInput(attrs={'class':'form-control'}),
            'moneda': forms.TextInput(attrs={'class':'form-control'}),
            'clabe': forms.TextInput(attrs={'class':'form-control'}),
            'banco2': forms.TextInput(attrs={'class':'form-control'}),
            'cuenta2': forms.TextInput(attrs={'class':'form-control'}),
            'moneda2': forms.TextInput(attrs={'class':'form-control'}),
            'clabe2': forms.TextInput(attrs={'class':'form-control'}),
            'constancia_situacion_fiscal': forms.FileInput(attrs={'class':'form-file'}),
            'estado_cuenta_bancario': forms.FileInput(attrs={'class':'form-file'}),
        }

class ProveedorDetailForm(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['empresa', 'tipo_alta', 'proveedor', 'contribuyente', 'razon_social', 'rfc', 'curp', 'regimen_capital', 'nombre_comercial', 'regimen_fiscal', 'uso_cdfi', 'representante_legal', 'correo_contacto', 'celular', 'correo_pagos', 'sitio_web', 'rubro', 'tipo_operacion', 'dias_credito', 'monto_credito', 'retencion_iva', 'retencion_isr', 'iva_frontera', 'calle', 'numero_exterior', 'numero_interior', 'codigo_postal', 'colonia', 'municipio', 'ciudad', 'estado', 'pais', 'banco', 'cuenta', 'moneda', 'clabe', 'banco2', 'cuenta2', 'moneda2', 'clabe2']
        widgets = {
            'empresa': forms.TextInput(attrs={'class':'form-control'}),
            'tipo_alta': forms.TextInput(attrs={'class':'form-control'}),
            'proveedor': forms.TextInput(attrs={'class':'form-control'}),
            'contribuyente': forms.TextInput(attrs={'class':'form-control'}),
            'razon_social': forms.TextInput(attrs={'class':'form-control'}),
            'rfc': forms.TextInput(attrs={'class':'form-control'}),
            'curp': forms.TextInput(attrs={'class':'form-control'}),
            'regimen_capital': forms.TextInput(attrs={'class':'form-control'}),
            'nombre_comercial': forms.TextInput(attrs={'class':'form-control'}),
            'regimen_fiscal': forms.TextInput(attrs={'class':'form-control'}),
            'uso_cdfi': forms.TextInput(attrs={'class':'form-control'}),
            'representante_legal': forms.TextInput(attrs={'class':'form-control'}),
            'correo_contacto': forms.TextInput(attrs={'class':'form-control'}),
            'celular': forms.TextInput(attrs={'class':'form-control'}),
            'correo_pagos': forms.TextInput(attrs={'class':'form-control'}),
            'sitio_web': forms.TextInput(attrs={'class':'form-control'}),
            'rubro': forms.TextInput(attrs={'class':'form-control'}),
            'tipo_operacion': forms.TextInput(attrs={'class':'form-control'}),
            'dias_credito': forms.TextInput(attrs={'class':'form-control'}),
            'monto_credito': forms.TextInput(attrs={'class':'form-control'}),
            'retencion_iva': forms.TextInput(attrs={'class':'form-control'}),
            'retencion_isr': forms.TextInput(attrs={'class':'form-control'}),
            'iva_frontera': forms.TextInput(attrs={'class':'form-control'}),
            'calle': forms.TextInput(attrs={'class':'form-control'}),
            'numero_exterior': forms.TextInput(attrs={'class':'form-control'}),
            'numero_interior': forms.TextInput(attrs={'class':'form-control'}),
            'codigo_postal': forms.TextInput(attrs={'class':'form-control'}),
            'colonia': forms.TextInput(attrs={'class':'form-control'}),
            'municipio': forms.TextInput(attrs={'class':'form-control'}),
            'ciudad': forms.TextInput(attrs={'class':'form-control'}),
            'estado': forms.TextInput(attrs={'class':'form-control'}),
            'pais': forms.TextInput(attrs={'class':'form-control'}),
            'banco': forms.TextInput(attrs={'class':'form-control'}),
            'cuenta': forms.TextInput(attrs={'class':'form-control'}),
            'moneda': forms.TextInput(attrs={'class':'form-control'}),
            'clabe': forms.TextInput(attrs={'class':'form-control'}),
            'banco2': forms.TextInput(attrs={'class':'form-control'}),
            'cuenta2': forms.TextInput(attrs={'class':'form-control'}),
            'moneda2': forms.TextInput(attrs={'class':'form-control'}),
            'clabe2': forms.TextInput(attrs={'class':'form-control'}),
        }

class ProveedorFormForStaff(forms.ModelForm):
    class Meta:
        model = Proveedor
        fields = ['empresa', 'tipo_alta', 'proveedor', 'contribuyente', 'razon_social', 'rfc', 'curp', 'regimen_capital', 'nombre_comercial', 'regimen_fiscal', 'uso_cdfi', 'representante_legal', 'correo_contacto', 'celular', 'correo_pagos', 'sitio_web', 'rubro', 'tipo_operacion', 'dias_credito', 'monto_credito', 'retencion_iva', 'retencion_isr', 'iva_frontera', 'calle', 'numero_exterior', 'numero_interior', 'codigo_postal', 'colonia', 'municipio', 'ciudad', 'estado', 'pais', 'banco', 'cuenta', 'moneda', 'clabe', 'banco2', 'cuenta2', 'moneda2', 'clabe2', 'compras', 'finanzas', 'sistemas']
        
        widgets = {
            'empresa': forms.TextInput(attrs={'class':'form-control'}),
            'tipo_alta': forms.TextInput(attrs={'class':'form-control'}),
            'proveedor': forms.TextInput(attrs={'class':'form-control'}),
            'contribuyente': forms.TextInput(attrs={'class':'form-control'}),
            'razon_social': forms.TextInput(attrs={'class':'form-control'}),
            'rfc': forms.TextInput(attrs={'class':'form-control'}),
            'curp': forms.TextInput(attrs={'class':'form-control'}),
            'regimen_capital': forms.TextInput(attrs={'class':'form-control'}),
            'nombre_comercial': forms.TextInput(attrs={'class':'form-control'}),
            'regimen_fiscal': forms.TextInput(attrs={'class':'form-control'}),
            'uso_cdfi': forms.TextInput(attrs={'class':'form-control'}),
            'representante_legal': forms.TextInput(attrs={'class':'form-control'}),
            'correo_contacto': forms.TextInput(attrs={'class':'form-control'}),
            'celular': forms.TextInput(attrs={'class':'form-control'}),
            'correo_pagos': forms.TextInput(attrs={'class':'form-control'}),
            'sitio_web': forms.TextInput(attrs={'class':'form-control'}),
            'rubro': forms.TextInput(attrs={'class':'form-control'}),
            'tipo_operacion': forms.TextInput(attrs={'class':'form-control'}),
            'dias_credito': forms.TextInput(attrs={'class':'form-control'}),
            'monto_credito': forms.TextInput(attrs={'class':'form-control'}),
            'retencion_iva': forms.TextInput(attrs={'class':'form-control'}),
            'retencion_isr': forms.TextInput(attrs={'class':'form-control'}),
            'iva_frontera': forms.TextInput(attrs={'class':'form-control'}),
            'calle': forms.TextInput(attrs={'class':'form-control'}),
            'numero_exterior': forms.TextInput(attrs={'class':'form-control'}),
            'numero_interior': forms.TextInput(attrs={'class':'form-control'}),
            'codigo_postal': forms.TextInput(attrs={'class':'form-control'}),
            'colonia': forms.TextInput(attrs={'class':'form-control'}),
            'municipio': forms.TextInput(attrs={'class':'form-control'}),
            'ciudad': forms.TextInput(attrs={'class':'form-control'}),
            'estado': forms.TextInput(attrs={'class':'form-control'}),
            'pais': forms.TextInput(attrs={'class':'form-control'}),
            'banco': forms.TextInput(attrs={'class':'form-control'}),
            'cuenta': forms.TextInput(attrs={'class':'form-control'}),
            'moneda': forms.TextInput(attrs={'class':'form-control'}),
            'clabe': forms.TextInput(attrs={'class':'form-control'}),
            'banco2': forms.TextInput(attrs={'class':'form-control'}),
            'cuenta2': forms.TextInput(attrs={'class':'form-control'}),
            'moneda2': forms.TextInput(attrs={'class':'form-control'}),
            'clabe2': forms.TextInput(attrs={'class':'form-control'}),
            'compras': forms.CheckboxInput(attrs={'class':'form-checkbox'}),
            'finanzas': forms.CheckboxInput(attrs={'class':'form-checkbox'}),
            'sistemas': forms.CheckboxInput(attrs={'class':'form-checkbox'}),
        }