from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Proveedor(models.Model):
    empresa = models.CharField(max_length=50)
    tipo_alta = models.CharField(max_length=20)
    proveedor = models.CharField(max_length=10)
    contribuyente = models.CharField(max_length=20)
    razon_social = models.CharField(max_length=50)
    rfc = models.CharField(max_length=13)
    curp = models.CharField(max_length=18, blank=True)
    regimen_capital = models.CharField(max_length=100)
    nombre_comercial = models.CharField(max_length=50)
    regimen_fiscal = models.CharField(max_length=100)
    uso_cdfi = models.CharField(max_length=100)
    representante_legal = models.CharField(max_length=50, blank=True)
    correo_contacto = models.CharField(max_length=30)
    celular = models.CharField(max_length=10)
    correo_pagos = models.CharField(max_length=30)
    sitio_web = models.CharField(max_length=30, blank=True)
    rubro = models.CharField(max_length=20)
    tipo_operacion = models.CharField(max_length=10)
    dias_credito = models.PositiveIntegerField(default=0)
    monto_credito = models.PositiveIntegerField(default=0)
    retencion_iva = models.CharField(max_length=10)
    retencion_isr = models.CharField(max_length=10)
    iva_frontera = models.CharField(max_length=10)
    calle = models.CharField(max_length=50)
    numero_exterior = models.CharField(max_length=10)
    numero_interior = models.CharField(max_length=10, blank=True)
    codigo_postal = models.CharField(max_length=5)
    colonia = models.CharField(max_length=50)
    municipio = models.CharField(max_length=30)
    ciudad = models.CharField(max_length=20)
    estado = models.CharField(max_length=20)
    pais = models.CharField(max_length=20)
    banco = models.CharField(max_length=50)
    cuenta = models.CharField(max_length=10)
    moneda = models.CharField(max_length=3)
    clabe = models.CharField(max_length=18)
    banco2 = models.CharField(max_length=50, blank=True)
    cuenta2 = models.CharField(max_length=10, blank=True)
    moneda2 = models.CharField(max_length=3, blank=True)
    clabe2 = models.CharField(max_length=18, blank=True)
    constancia_situacion_fiscal = models.FileField(upload_to='documentos/constancias/')
    estado_cuenta_bancario = models.FileField(upload_to='documentos/estados_cuenta')
    compras = models.BooleanField(default=False)
    finanzas = models.BooleanField(default=False)
    sistemas = models.BooleanField(default=False)
    aprobadas = models.BooleanField(default=False)
    fecha = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id) + " - " + self.razon_social + " - " + self.usuario.username